name: Test and Build Workflow
# This workflow is triggered on pull requests to master or a opendistro release branch
on:
  pull_request:
    branches:
      - main
      - opendistro-*
      - plugin-dev
  push:
    branches:
      - main
      - opendistro-*
      - plugin-dev

jobs:
  build:
    # Job name
    name: Build Asynchronous Search
    # This job runs on Linux. TODO Make it work for other OS distributions
    runs-on: ubuntu-latest
    steps:
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: Checkout Branch
        uses: actions/checkout@v2
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload failed logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: build/testclusters/integTest-*/logs/*
      - name: Create Artifact Path
        run: |
          mkdir -p asynchronous-search-artifacts
          cp ./build/distributions/*.zip asynchronous-search-artifacts     
      - name: Uploads coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # This step uses the upload-artifact Github action: https://github.com/actions/upload-artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: asynchronous-search-plugin
          path: asynchronous-search-artifacts
