name: Build and Test Opendistro asynchronous search
on:
  push:
    branches:
      - master
      - opendistro-*

jobs:
  Build-opendistro-asynchronous-search:
    strategy:
      matrix:
        java: [14]

    name: Build and Test Asynchronous Search Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout asynchronous search
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew build
